### ISSUE TITLE
questionnaire migration: is it a bug or???

### ISSUE THREAD

**Issue by froggypaule** [DataStewardshipPortal/dsp-common#247]
**self-installed 3.10**

**Describe the bug**
A questionnaire migration to the next version of the KM. It shows 
![Screenshot from 2022-04-12 10-44-54](https://user-images.githubusercontent.com/47455219/162919981-0ac8432f-11c4-4b61-816b-cf37b1cfb715.png)

This really comes out of the blue, and I am lost :(  I can see an error in the log
[log.txt](https://github.com/ds-wizard/ds-wizard/files/8471283/log.txt)
but it doesn't help me....

What on earth could have happened?
Thanks!

**Comment by froggypaule** [comment]
I comes from my side, but I have no clue about the how etc.... I keep looking.

**Comment by froggypaule** [comment]
It has to do with the answers given: if I create a (empty: without given answers) project from IFB:bioimage-fbi-embrc-pgd-structure-km:1.3.9 and then migrate it to IFB:bioimage-fbi-embrc-pgd-structure-km:1.3.10 it all goes well.
Here I join the km 
[IFB bioimage-fbi-embrc-pgd-structure-km 1.3.10.txt](https://github.com/ds-wizard/ds-wizard/files/8479565/IFB.bioimage-fbi-embrc-pgd-structure-km.1.3.10.txt)
and the project with answers that creates the bug 
[testing of new insight template.txt](https://github.com/ds-wizard/ds-wizard/files/8479574/testing.of.new.insight.template.txt)

This project is actually a clone from an existing project filled by users.

**Comment by MarekSuchanek** [comment]
Status update: being investigated via email conversation due to personal data included. We will post here info about the issue when it is resolved.
