### ISSUE TITLE
problems in editing KM

### ISSUE THREAD

**Issue by froggypaule** [DataStewardshipPortal/dsp-common#284]
### What web browser is used when the issue appears?

Firefox

### How are you using DSW while encountering the issue?

- [x] Testing on localhost (dsw-deployment-example)
- [ ] Using DSW managed by someone else (specify in text)
- [X] Using DSW that I manage

### What parts of DSW are affected?

- [ ] Dashboard
- [ ] Documents
- [ ] Document Template Editors
- [ ] Document Templates
- [ ] Locales
- [X] Knowledge Model Editors
- [ ] Knowledge Models
- [ ] Project Importers
- [ ] Projects
- [ ] Settings
- [ ] Users and Authentication

### Version

```plain text
Client
Version: v4.3.0~5aeed37
Built at: 2024-02-06T08:11:32Z
---
Serveur
Version: v4.3.0~10b178c7
Built at: 2024-02-06T08:05:10Z
---
Document Worker
Version: v4.3.0~4d1ca3f
Built at: 2024-02-06T04:50:01Z
---
Mailer
Version: v4.3.0~4d1ca3f
Built at: 2024-02-06T04:49:56Z
```

### What happened?

This is a behaviour I have noticed a while back (years), but didn't report because I couldn't characterise it. And I still can't, but since it can become a serious hindrance, I'll report it now.

The situation is that of editing a KM. Suppose I am adding new questions with a title, choices if multi-choice, or answers if option, or item questions if item list.
This new question might lose its title, or its dependencies (choices or options or item questions) in two cases:
- when one is updating the settings (version number and README): once the update is saved, the new question may be in a state without title etc...
- or when one is publishing: the next KM version might show  that the concerned question in a state without title etc... 
All this implies (almost always) to redo all the work, and at times publish the KM a few times to get it complete.

Now, there is no way I can characterise this behaviour etc... but it is seriously painful. Unless you have heard of similar issues before, or have any ideas how to help me here?
Thanks!!!

**Comment by froggypaule** [comment]
Hello all!

I have noticed that this behaviour seems to have disappeared since the latest releases (definitely 4.5, maybe 4.4).
Can you confirm this?

In any case, KM editing is now seamless.

**Comment by krystofkomanec** [comment]
I haven't seen that issue in a while either. It's good if it's gone, though we're not sure what caused it in the first place. I will close this issue for now, let me know if you encouter it again.

**Comment by froggypaule** [comment]
Well, thank you, I am glad this problem seems to have 'disappeared'...
