### ISSUE TITLE
[Bug] ROR Integration fuses multiple institution names in one string

### ISSUE THREAD

**Issue by M-casado** [DataStewardshipPortal/dsp-common#285]
### What web browser is used when the issue appears?

Chrome

### How are you using DSW while encountering the issue?

- [ ] Testing on localhost (dsw-deployment-example)
- [X] Using DSW managed by someone else (specify in text)
- [ ] Using DSW that I manage

### What parts of DSW are affected?

- [ ] Dashboard
- [X] Documents
- [ ] Document Template Editors
- [ ] Document Templates
- [ ] Locales
- [ ] Knowledge Model Editors
- [X] Knowledge Models
- [ ] Project Importers
- [X] Projects
- [ ] Settings
- [ ] Users and Authentication

### Version

```plain text
Client
Version: v4.4.0~f9d9c7a
Built at: 2024-03-05T08:28:42Z
---
Server
Version: v4.4.0~0f8e9e5e
Built at: 2024-03-05T08:28:50Z
---
Document Worker
Version: v4.4.0~aa087a1
Built at: 2024-03-05T07:57:42Z
---
Mailer
Version: v4.4.0~aa087a1
Built at: 2024-03-05T07:57:32Z
```

### Summary
The error revolves around how the ROR integration into the DSW treats institution acronyms: I've noticed that not all "Other names", but the ones that seem like **acronyms**, are **joined together in a single string**. 

### Steps to reproduce
1. Open DSW instance and create a new project.
2. Fill out the **``Affiliation`` of a ``Contributor``** (within ``I. Administrative information``) with an institution that in ROR has **multiple acronyms as "Other names"**. For example, the [**EMBL-EBI**](https://ror.org/02catss52) or **[CMA](https://ror.org/051rrf637)**. 
![image](https://github.com/ds-wizard/ds-wizard/assets/77288380/bd031c54-1081-4595-94b7-7c2b585b93d9)
3. Click on the institution, and notice how the **institution acronym is malformed**: it should be ``EMBL-EBI``, but its fused as ``EBIEMBL-EBI``).
![image](https://github.com/ds-wizard/ds-wizard/assets/77288380/e0b0f9cb-3f00-4052-9cd5-6ac3efa7ca1b)
4. Create a document from that project, and that error is propagated as well to the document.

**Comment by krystofkomanec** [comment]
Hi @M-casado, thank you for reporting this issue.

I have fixed it in the integration, so now it will only take into account the first acronym if there are multiple.

A new version of the Knowledge Model has been published to the Registry: https://registry.ds-wizard.org/knowledge-models/dsw:root:2.6.4
