### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by JKratto** [DataStewardshipPortal/dsp-common#288]
### What web browser is used when the issue appears?

Chrome

### How are you using DSW while encountering the issue?

- [ ] Testing on localhost (dsw-deployment-example)
- [ ] Using DSW managed by someone else (specify in text)
- [X] Using DSW that I manage

### What parts of DSW are affected?

- [ ] Dashboard
- [X] Documents
- [ ] Document Template Editors
- [ ] Document Templates
- [ ] Locales
- [ ] Knowledge Model Editors
- [ ] Knowledge Models
- [ ] Project Importers
- [ ] Projects
- [ ] Settings
- [ ] Users and Authentication

### Version

```plain text
4.7
```

### What happened?

On a fresh install, I was unable to load DSW as I got 404 on two resources:
`/configs/bootstrap`
`/configs/locales/en`
This results in the error:
"Bootstrap Error
Server responded with an error code 404.
Please, contact the application provider."

This was cased by me missing the `/wizard-api` part of the URI in ENV of the wizard-client `API_URL: https://api.dsw.domain.cz/wizard-api`. After adding it, it started working flawlessly. It might indicate some other problem, as this, from my point of view, should not be needed.

The second problem came from me not understanding enough S3, and thus, I put the minio behind URI, such as `https://dsw.domain.cz/s3`, which is by S3 API documentation incorrect. This was relatively easy, but I recommend mentioning it in the docs—URIs such as `https://s3.dsw.domain.cz/` work fine.

Also, the fact (even though making sense) that the API itself must be accessible from the internet (from the user-client) is worth mentioning in the docs. It's also an easy fix but unnecessary. For S3, it is mentioned somewhere in the docs, which is helpful.

**Comment by krystofkomanec** [comment]
Hi @JKratto, I checked your issues:

1. `wizard-api` was indeed missing in the documentation, I fixed it, it will be released in next version of documentaion.
2. The other issues should be part of MinIO documentation. As MinIO is only one of possible object storages, our other users use also Azure, AWS or Google Cloud, so corresponding documentation should be used.

Thank you for the feedback!
