### ISSUE TITLE
Password Reset not working

### ISSUE THREAD

**Issue by JKratto** [DataStewardshipPortal/dsp-common#289]
### What web browser is used when the issue appears?

Chrome

### How are you using DSW while encountering the issue?

- [ ] Testing on localhost (dsw-deployment-example)
- [ ] Using DSW managed by someone else (specify in text)
- [X] Using DSW that I manage

### What parts of DSW are affected?

- [ ] Dashboard
- [ ] Documents
- [ ] Document Template Editors
- [ ] Document Templates
- [ ] Locales
- [ ] Knowledge Model Editors
- [ ] Knowledge Models
- [ ] Project Importers
- [ ] Projects
- [ ] Settings
- [X] Users and Authentication

### Version

```plain text
4.7
```

### What happened?

When I try start the "Forgotten Password" flow, I receive an email, but after clicking the link (even in private mode or a different browser) I am eventually redirected to the login page without being able to reset my password (set a new one) or without any guidance what should I do next.

**Comment by krystofkomanec** [comment]
Hi @JKratto, this looks like a deployment issue. I tested it and for me the reset password link works correctly. Could you send us the link from the reset password email?

**Comment by JKratto** [comment]
Thank you @krystofkomanec. Here is the example link.
https://dsw.domain.cz/forgotten-password/5e59f94a-d2ff-40ad-a63c-4031c1edf251/4f551e62-e3e8-473a-b9a6-829dfa135e9c

Meanwhile I have redeployed dsw from scratch and the issue persists.

**Comment by krystofkomanec** [comment]
Ok. The issue you have is that the url is missing `/wizard`. I will fix it in the documentation. What you need to do is to set the `general.clientUrl` in `application.yml` to include `/wizard`.

See the deployment example here: https://github.com/ds-wizard/dsw-deployment-example/blob/main/config/application.yml

Btw you can also update to version 4.8 that was just released.

**Comment by JKratto** [comment]
Based on my previous experience, I could have thought of that. :) I'll reconfigure and deploy try the upgrade.

**Comment by JKratto** [comment]
I can confirm, that this solved my issue. Also upgrade went smoothly. Thank you for your help. 🙂

**Comment by krystofkomanec** [comment]
Glad to hear that. Thanks to you we also improved the documentation, so likewise.
