### ISSUE TITLE
item select question href and Questionnaire Report

### ISSUE THREAD

**Issue by froggypaule** [DataStewardshipPortal/dsp-common#290]
### What is your question?

```Client
Version: v4.10.1~d8d97f7
Built at: 2024-09-10T08:00:09Z
---
Serveur
Version: v4.10.0~ca877664
Built at: 2024-09-03T06:27:44Z
what is bc1d8214-7aee-490e-883c-1c04e3469922
---
Document Worker
Version: v4.10.6~d3420d2
Built at: 2024-09-16T12:28:01Z
---
Mailer
Version: v4.10.6~d3420d2
Built at: 2024-09-16T12:28:11Z
```

I am playing around with the Item Select question type, updating the document models and I noticed the following:

Investigating  `renderAnswerItemSelect` we see that answer is output as 
`<a href="#item-{{ question.list_question_uuid }}-{{ reply.item_uuid }}">{{ reply.item_title }}</a>`

Indeed this output nicely gives a link to the proper item when one does filling in the project, but it won't work when doing a preview or creating a document, as the full path is required (Chapter + ...).
Just asking, I guess that in the current state of the document worker, it is not possible to have access to this information? 

Thanks!

**Comment by froggypaule** [comment]
Actually I think I am talking non-sense when mentioning the item link when filling in the project: it has absolutely nothing to do with document context.
So I guess my question is simpler: the link as given above cannot work, unless there is a means to resolve `#item` ...

**Comment by MarekSuchanek** [comment]
I am not totally sure what do you mean here...

```
<a href="#item-{{ question.list_question_uuid }}-{{ reply.item_uuid }}">{{ reply.item_title }}</a>
```

It is just an internal link within the document which should work both in the Preview as well as in downloaded document (PDF and HTML).

If you would need an external direct link to the questionnaire item (not inside the document but to the questionnaire), then you can construct the link but you would need to know the entire path.

**Comment by froggypaule** [comment]
...  mmm... I don't think the link works for the preview; let me go back to it and have another look.
Yes it is an internal link I agree.

**Comment by froggypaule** [comment]
Forgive me, I was wrong, I don't know what I was thinking....
