### ISSUE TITLE
KM update problem: losing the parent

### ISSUE THREAD

**Issue by froggypaule** [DataStewardshipPortal/dsp-common#291]
### What web browser is used when the issue appears?

Firefox

### How are you using DSW while encountering the issue?

- [ ] Testing on localhost (dsw-deployment-example)
- [ ] Using DSW managed by someone else (specify in text)
- [X] Using DSW that I manage

### What parts of DSW are affected?

- [ ] Dashboard
- [ ] Documents
- [ ] Document Template Editors
- [ ] Document Templates
- [ ] Locales
- [X] Knowledge Model Editors
- [X] Knowledge Models
- [ ] Project Importers
- [ ] Projects
- [ ] Settings
- [ ] Users and Authentication

### Version

```plain text
Client
Version: v4.10.1~d8d97f7
Built at: 2024-09-10T08:00:09Z
---
Serveur
Version: v4.10.0~ca877664
Built at: 2024-09-03T06:27:44Z
---
Document Worker
Version: v4.10.6~d3420d2
Built at: 2024-09-16T12:28:01Z
---
Mailer
Version: v4.10.6~d3420d2
Built at: 2024-09-16T12:28:11Z
```

### What happened?

Hello all!
I am afraid we (myself and @Frédéric Brau) are getting mad... I'll try to explain as best as I can.

We have a KM `https://dsw.france-bioinformatique.fr/wizard/knowledge-models/IFB:ifb-facility-dmp-en:0.1.6` with parent `[IFB:pgd-structure:2.6.4](https://dsw.france-bioinformatique.fr/wizard/knowledge-models/IFB:pgd-structure:2.6.4)`:

![Screenshot from 2024-09-26 15-13-21](https://github.com/user-attachments/assets/fa13f376-baec-48ca-9d99-43b6f3d73fd5)

`IFB:ifb-facility-dmp-en` is our ongoing English translation of our KM `IFB:pgd-structure` which we have been developing for 5 years now. 
Normally when opening up an editor, updating something in `IFB:ifb-facility-dmp-en`, and publishing it you wouldn't expect your parent to change right?

Let's open an editor for `IFB:ifb-facility-dmp-en:0.1.6`
The editor looks like 
![Screenshot from 2024-09-26 15-24-24](https://github.com/user-attachments/assets/83139195-bc80-4329-ab19-f0398007552b)
So far so good!

Also we see (settings): 
![Screenshot from 2024-09-26 15-25-42](https://github.com/user-attachments/assets/dad3bfb2-f036-4a07-b092-5435105ce69c)

and 
![Screenshot from 2024-09-26 15-25-54](https://github.com/user-attachments/assets/980e3d93-8e60-4c81-b776-6b773eac20f4)

Still good. Now let's publish this under V0.1.7, without doing any changes; we update the settings 
![Screenshot from 2024-09-26 15-28-11](https://github.com/user-attachments/assets/37900b59-5e7f-4a1c-8408-157d04f7dcbf)
and we check that we still have 
![Screenshot from 2024-09-26 15-28-44](https://github.com/user-attachments/assets/bcce538e-9061-4b25-99ad-5f8f638f6495)

We publish
![Screenshot from 2024-09-26 15-29-44](https://github.com/user-attachments/assets/6ef47f6b-a621-4b15-8a9f-ad715827ad63)

 Here is what we see, in the KM view
![Screenshot from 2024-09-26 15-30-40](https://github.com/user-attachments/assets/7ee8dc0c-59dd-4ac3-9704-9d6355eb3aff)

and the editor view 
![Screenshot from 2024-09-26 15-31-28](https://github.com/user-attachments/assets/0f2e8f42-d4df-4a05-a8d6-675cbd1db49f)

So indeed the parent changed... and the editor view tells me an update is available.

**Comment by froggypaule** [comment]
So this is completely crazy... the problem we really need `IFB:ifb-facility-dmp-en` in its current state and with the original parent, since the point of course is to translate as our parent evolves.

When I look at the two last packages in IFB:ifb-facility-dmp-en:0.1.7, I see
```      "forkOfPackageId": "IFB:pgd-structure:2.6.4",
      "id": "IFB:ifb-facility-dmp-en:0.1.6",
      "kmId": "ifb-facility-dmp-en",
      "license": "CC-BY 4.0",
      "mergeCheckpointPackageId": "IFB:ifb-facility-dmp-en:0.1.6",
      "metamodelVersion": 15,
      "name": "IFB Facility DMP (EN)",
      "nonEditable": false,
      "organizationId": "IFB",
      "phase": "ReleasedPackagePhase",
      "previousPackageId": "IFB:ifb-facility-dmp-en:0.1.5",
      "readme": "\n# Création d'une trame de PGD (structure) ; une collaboration de l'IFB, le FBI et EMBRC-FR et du MuDiS4LS\n\n\n## Changelog\n\n### 0.1.6\nUpdate to 0.1.6 due to modifications in parent 2.6.3 to 2.6.4\n\n### 0.1.5\nTranslation finished 24/09/24. Checking translation homogeneity\n\n### 0.1.4\nTranslation continued 10/09/24 and all questions are translated. Comments translation continued.\n\n### 0.1.2\nTranslation continued 23/07/24 and all questions are translated. Comments translation continued.\n\n### 0.1.1\nTranslation continued 16/07/24 and all questions are translated. Comments translation started\n\n### 0.1.0\nTranslation continued 12/07/24 and all questions are translated. The comments should be done now\n\n### 0.0.8\nTranslation continued 05/07/24\n\n### 0.0.7\nTranslation continued 25/06/24\n\n### 0.0.6\nTranslation continued 25/06/24\n\n### 0.0.5\nRe-translation from the beginning ++ 17/06/24\n\n### 0.0.4\nRe-translation from the beginning +\n\n### 0.0.3 \nRe-translation from the beginning\n\n### 0.0.2 \nminor modifications\n### 0.0.1\n\n- clone of IFB:pgd-structure:2.6.3",
      "version": "0.1.6"
    },
    {
      "createdAt": "2024-09-26T13:30:25.481204Z",
      "description": "Trame PGD structure, une extension du projet PGD FBI-EMBRC-IFB",
      "events": [],
      "forkOfPackageId": "IFB:ifb-facility-dmp-en:0.1.6",
      "id": "IFB:ifb-facility-dmp-en:0.1.7",
      "kmId": "ifb-facility-dmp-en",
      "license": "CC-BY 4.0",
      "mergeCheckpointPackageId": "IFB:pgd-structure:2.6.4",
      "metamodelVersion": 15,
      "name": "IFB Facility DMP (EN)",
      "nonEditable": false,
      "organizationId": "IFB",
      "phase": "ReleasedPackagePhase",
      "previousPackageId": "IFB:ifb-facility-dmp-en:0.1.6",
      "readme": "\n# Création d'une trame de PGD (structure) ; une collaboration de l'IFB, le FBI et EMBRC-FR et du MuDiS4LS\n\n\n## Changelog\n\n### 0.1.7 Test\n\n### 0.1.6\nUpdate to 0.1.6 due to modifications in parent 2.6.3 to 2.6.4\n\n### 0.1.5\nTranslation finished 24/09/24. Checking translation homogeneity\n\n### 0.1.4\nTranslation continued 10/09/24 and all questions are translated. Comments translation continued.\n\n### 0.1.2\nTranslation continued 23/07/24 and all questions are translated. Comments translation continued.\n\n### 0.1.1\nTranslation continued 16/07/24 and all questions are translated. Comments translation started\n\n### 0.1.0\nTranslation continued 12/07/24 and all questions are translated. The comments should be done now\n\n### 0.0.8\nTranslation continued 05/07/24\n\n### 0.0.7\nTranslation continued 25/06/24\n\n### 0.0.6\nTranslation continued 25/06/24\n\n### 0.0.5\nRe-translation from the beginning ++ 17/06/24\n\n### 0.0.4\nRe-translation from the beginning +\n\n### 0.0.3 \nRe-translation from the beginning\n\n### 0.0.2 \nminor modifications\n### 0.0.1\n\n- clone of IFB:pgd-structure:2.6.3",
      "version": "0.1.7"
    }
  ],
  "version": "0.1.7"
```

a strange setting for `"mergeCheckpointPackageId": "IFB:pgd-structure:2.6.4"`.

Please tell us there is a simple answer; for privacy reasons I send you the two km dumps (json files).
Many thanks!!!

**Comment by froggypaule** [comment]
I must add that this only happens for this km....   :(

**Comment by vknaisl** [comment]
Hello,

Are you sure that you did not edit (in JSON or in DB) the knowledge model manually in the past? 

Vojtech

**Comment by froggypaule** [comment]
Certain, we never did this.
Somehow we always had problems (I guess due to our mistakes) but managed to recover the parent (by deleting the offending versions et starting anew). Once we re-started from scratch altogether.


I cannot send the kms, the files are too big...

**Comment by froggypaule** [comment]
Let's try to send the files here (after all, the whole lot is meant to be published, so there is no GDPR issues). 
[IFB_ifb-facility-dmp-en_0.1.6.txt](https://github.com/user-attachments/files/17149846/IFB_ifb-facility-dmp-en_0.1.6.txt)
[IFB_ifb-facility-dmp-en_0.1.7.txt](https://github.com/user-attachments/files/17149848/IFB_ifb-facility-dmp-en_0.1.7.txt)

**Comment by vknaisl** [comment]
Fixed via email.

**Comment by froggypaule** [comment]
Hello @vknaisl , thanks for this :+1: 
I have a question: what is the field "mergeCheckpointPackageId" for? how does it work? Maybe you have some doc on this?
Cheers!

**Comment by vknaisl** [comment]
Hello @froggypaule, 

It's internal thing together with internal structure of knowledge model. It should never be exposed to user to ensure that no one will try to edit it. That's why we don't have in our guide. These properties primarly serves for correct parent-child updates.

Regards,
Vojtech

**Comment by froggypaule** [comment]
:+1:
