### ISSUE TITLE
Bug appears

### ISSUE THREAD

**Issue by priya-gitTest** [DataStewardshipPortal/dsp-common#294]
### What web browser is used when the issue appears?

Edge

### How are you using DSW while encountering the issue?

- [ ] Testing on localhost (dsw-deployment-example)
- [X] Using DSW managed by someone else (specify in text)
- [ ] Using DSW that I manage

### What parts of DSW are affected?

- [ ] Dashboard
- [ ] Documents
- [ ] Document Template Editors
- [ ] Document Templates
- [ ] Locales
- [ ] Knowledge Model Editors
- [ ] Knowledge Models
- [ ] Project Importers
- [X] Projects
- [X] Settings
- [ ] Users and Authentication

### Version

```plain text
Client
Version	v4.12.0~0f0ae3c
Built at	7. 11. 2024, 10:34
Server
Version	v4.12.0~8335b450
Built at	7. 11. 2024, 14:04
API URL	https://smw.dsw.elixir-europe.org/wizard-api
API Docs	https://smw.dsw.elixir-europe.org/wizard-api/swagger-ui/
Document Worker
Version	v4.12.0~f6f9756
Built at	7. 11. 2024, 10:42
Mailer
Version	v4.12.0~f6f9756
Built at	7. 11. 2024, 10:42
```

### What happened?

It was dearlier possible to make PDG exports for the SMP but somehow its not possible now. I played around with the types of templates too but nothing works.

![image](https://github.com/user-attachments/assets/5166f73c-293c-4982-851f-93388a5961b2)
![image](https://github.com/user-attachments/assets/d935a7f1-cc03-4311-8206-168186be20b0)

**Comment by krystofkomanec** [comment]
Hi Priya, this issue is caused by the template not being updated for latest DSW. Please contact someone who manages that in your instance.

**Comment by priya-gitTest** [comment]
Hi
Kryštof

We don’t manage it ourselves, but perhaps Elixir. I will look into it and
get back to you.

Regards
Priyanka

**Comment by krystofkomanec** [comment]
Sorry for confusion, apparently it should be already fixed.
Kryštof
