### ISSUE TITLE
Brocken link in DSW guide

### ISSUE THREAD

**Issue by marikapop** [DataStewardshipPortal/dsp-common#295]
### How are you using DSW while encountering the issue?

- [ ] Testing on localhost (dsw-deployment-example)
- [ ] Using DSW managed by someone else (specify in text)
- [ ] Using DSW that I manage

### What parts of DSW are affected?

- [ ] Dashboard
- [ ] Documents
- [ ] Document Template Editors
- [ ] Document Templates
- [ ] Locales
- [ ] Knowledge Model Editors
- [ ] Knowledge Models
- [ ] Project Importers
- [ ] Projects
- [ ] Settings
- [ ] Users and Authentication

### Version

```plain text
This is the issue with user guide not actual DSW
```

### What happened?

Page [Step: pandoc](https://guide.ds-wizard.org/en/latest/more/development/document-templates/steps/pandoc.html) in Notes sections refers to addons directory. This link rises 404 error.
![image](https://github.com/user-attachments/assets/1818a76d-03b2-436a-92f8-c052e035d4e5)

**Comment by krystofkomanec** [comment]
Dear Marina,

thank you for reporting, I will fix it.

**Comment by krystofkomanec** [comment]
In the end I removed the link, it was outdated content. Thank you for reporting.
